version: '3.1'

services:
  web:  
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    container_name: finance-quotes

    ports:
     - "5000:5000"
    volumes:
      - .:/web
      - node_modules:/web/node_modules

volumes:
  node_modules:
